### ISSUE TITLE
why does this crate need to be generic over an exporter?

### ISSUE THREAD

**Issue by cbeck88** [Ptrskay3/axum-prometheus#55]
i don't understand right now why this crate needs to be aware of or be generic over the metrics exporter.

at a high level, what it seems it should do is:

* be a middleware layer in axum / tower that tracks request / response lifecycle
* pubish metrics into the metrics.rs ecosystem

to do this, all it should need is:

* enough dependencies in axum / tower to track requests and responses
* access to the `metrics` facade so that it can publish data into that ecosystem

and indeed, it seems that the code only uses the `metrics!` macros to actually report data

https://github.com/Ptrskay3/axum-prometheus/blob/aaf0a29215837a9bab10e9af3dd216a01d3c76ee/src/lib.rs#L464
https://github.com/Ptrskay3/axum-prometheus/blob/master/src/lib.rs#L218

---

However, that's not how the API that's actually exposed works. To use the crate, I have to commit to a specific metrics backend and tell your code what it is. I have to either use `PrometheusMetricsLayer` or I have to use `GenericMetricLayer` and then pass the backend as a generic, and wrap all of it's types with your traits.

Why?

Your code doesn't actually depend on what metrics backend I choose at all. It only pipes data to `metrics::counter!` and `metrics::gauge!` which is already going to work for any metrics backend I choose.

I understand that some backends are pull (prometheus) and some are push (statsd), and so some of them have a handle that's needed to implement the metrics scrape endpoint, and for some of them that isn't really needed. Regardless, your crate doesn't actually do anything with the handle -- it's my job as the user of your API to add a route to my axum server.

So then, why do you bother creating types for the handle, or traits around how it is created, if you don't do anything with it? Why not leave the initialization of the backend entirely to the user of your crate, and only rely on the `metrics` facade crate to send data?

In short, unless I've missed something, I want to propose a refactor

* Get rid of `PrometheusMetricLayer`, `GenericMetricLayer`. Drop all types related to `Handle`, `::pair`, etc.
* Just have something like `AxumMetricLayer`, which hooks into the life-cycle, publishes metrics using the `metrics` crate macros, and that's it, and has no information or dependencies about the metrics backend.
* Document that the recorder has to be set before `AxumMetricLayer` is used (but this is obvious also from the docu of the `metrics` crate)
* Drop all your dependencies on `metrics-exporter-prometheus` etc. This will make it easier for downstream because in the `metrics` ecosystem, the `metrics` crate has a global variable for the recorder, and if multiple versions of `metrics` crate are pulled into your program, you get screwed by having multiple versions of this global variable and you end up with dropped `metrics`. The more different paths from your crate to `metrics` the more likely it is for your users to get bitten by this issue. https://users.rust-lang.org/t/can-cargo-warn-about-linking-multiple-versions-of-a-crate/76447

This will also make your crate much more easily testable because you can just set up a test recorder in a unit test, and you can use the same code that you would use for Prometheus or anything else and evaluate how well it works.

**Comment by Ptrskay3** [comment]
The short answer to your almost all of your questions: because that's the path I chose when I created this library.

 I wanted to target a high level API with reasonable defaults that just works for "most" users. I believe having to just write `::pair` is very powerful — if it fits your use case. That being said, most of the stuff should be configurable, and users should be able to drop down to lower level APIs if the default behaviour doesn't work for them. This may lack some configuration options here and there, the API may not be the best fit for some use cases, but I do think this is mostly true for this crate: you can even re-implement the whole middleware logic with the `lifecycle` API (despite the fact there's no example or guide for it currently).  

> Document that the recorder has to be set before `AxumMetricLayer` is used (but this is obvious also from the docu of the metrics crate)

Documenting that something needs to be done is much more likely to be missed compared to an API that's enforcing it.

> Regardless, your crate doesn't actually do anything with the handle -- it's my job as the user of your API to add a route to my axum server.

Automatically registering a route to axum's Router — as far as I can remember — is problematic.   I'm not fully up to date in this topic, I may be wrong.
The real reason I haven't even attempted to address this is that it'd be very confusing in my opinion. Some stuff is better to be left explicit.

In my opinion most of what you proposed is more or less possible to achieve now. 
- I'd keep `PrometheusMetricLayer`, `GenericMetricLayer` and all the rest. What about a new API level as a common middle ground, just like the `AxumMetricLayer` you mentioned?
- You don't need to pull in `metrics_exporter_prometheus`, if you disable the default features. This will also disable everything that's Prometheus related. However, `GenericMetricLayer` requires that you wrap your exporter into our traits, that's true. If you don't like this style, I'm open to suggestions, but I'd like to enforce the initialization with the API design, just like it's now.
- Dropping the dependency completely on `metrics_exporter_prometheus`, when literally this crate's name is `axum-prometheus` certainly would be a funny thing to do.  :smile:  `metrics` and `metrics_exporter_prometheus` are hopefully kept in sync within this crate, and we have 
https://github.com/Ptrskay3/axum-prometheus/blob/aaf0a29215837a9bab10e9af3dd216a01d3c76ee/src/lib.rs#L226-L228
so people will have to really try hard to misuse it. 

Testing is something I had near zero time to tackle with, but [`metris-util`](https://crates.io/crates/metrics-util) is something we could totally take advantage of, and we should be able to remove that horrible snapshot smoke testing stuff I made earlier.

Overall, I think what you're proposing here is just too much all at once. Don't get me wrong, I appreciate you raising my attention to some issues, but this almost sounds like what you really want is new crate.

**Comment by cbeck88** [comment]
Thanks for the response, this all checks out, and I'm glad I didn't seriously misunderstand what's going on in this crate

I started using this crate for the very first axum server I ever used, and I started googling like, how do I get relevant metrics from axum for prometheus. And there is nothing else out there that looks as straightforward as this crate that you will find. So kudos to you for that, and thanks

Where I'm running into trouble now is, I need to be able to change the backend dynamically between prometheus and datadog, and it becomes a lot more complicated than it might be otherwise because this crate is also tied to the backend.

I still maintain, even if you don't make radical changes to the API, if there isn't a reason in the implementations that `PrometheusMetricLayer` or `GenericMetricLayer` need to know what the backend is, then they probably shouldn't be generic over that parameter. You could still have `Handle` objects and the `Handle` could have a pair function, but what might be cool is if the actual metric layer for `Prometheus` and for `Generic` is actually just `AxumMetricsLayer` and it's agnostic about the backend. Then you are still having the option to provide help with initialization, but it makes it simpler for the user, because they don't have type-changing metric layers depending on their config which makes the initialization functions more complicated.

**Comment by cbeck88** [comment]
The question I have for myself now is basically, why don't I just follow this example from axum crate to connect it to the metrics facade, without coupling to the metrics backend:

https://github.com/tokio-rs/axum/blob/main/examples/prometheus-metrics/src/main.rs#L93

and then setup the metrics backend, and the prometheus route using the handle in case of prometheus, however I want elsewhere in the program.

I guess that I'm going to lose some of the additional metrics you are computing if I do that but it might make it simpler as I experiment with alternative backends.

**Comment by cbeck88** [comment]
Also there might be a world where you gate different parts of this on features, for example, you might be able to expose a fully backend-agnostic `AxumMetricsLayer` which is available with `default-features = false`, and have a prometheus feature that is on by default, but also can be turned off

**Comment by Ptrskay3** [comment]
Yes, it may be a good direction to take, but first I need to experiment how a backend agnostic API feels like. There're a lot going on for me right now, so I may be slow to take on this, but I'll definitely create some issues at least. If you're allowed to share some details (or code) about your use case, that'd be a huge help.

and to reply to your last two comments:

> Also there might be a world where you gate different parts of this on features, for example, you might be able to expose a fully backend-agnostic AxumMetricsLayer which is available with default-features = false, and have a prometheus feature that is on by default, but also can be turned off

Yes, that's perfectly reasonable. That's how `PrometheusMetricLayer` is set up right now, if you look at it. 

> The question I have for myself now is basically, why don't I just follow this example from axum crate to connect it to the metrics facade, without coupling to the metrics backend:
https://github.com/tokio-rs/axum/blob/806bc26e62afc2e0c83240a9e85c14c96bc2ceb3/examples/prometheus-metrics/src/main.rs#L93

You can definitely follow this path, and skip `axum-prometheus`, but you will lose some metrics, because it cannot hook into the subtle details of a request as a simple middleware function — that's why I use the `tower::Service` trait .

 In fact, the [`Traffic`](https://docs.rs/axum-prometheus/0.6.1/axum_prometheus/struct.Traffic.html) struct tracks all metrics in this crate, so you may take a look at its `OnBodyChunk` and `Callbacks` implementation.

**Comment by cbeck88** [comment]
Thanks again, will keep reading and thinking

**Comment by Ptrskay3** [comment]
Just merged #56, that should address your concerns.
