### ISSUE TITLE
Failing to build metrics exporter in tests

### ISSUE THREAD

**Issue by Rolv-Apneseth** [Ptrskay3/axum-prometheus#59]
Hey. Thanks for making this. I'm having an issue and was hoping I could get some help.

I'm having an issue with my tests (using `axum-test`) where having multiple test functions in the same file causes the tests to fail by being unable to install the metrics recorder. Example integration test file:

```rust
mod common;
use common::get_server;

#[tokio::test]
async fn test_404() {
    let server = get_server();

    let response = server.get("not-a-route").await;
    response.assert_status_not_found();
    response.assert_text_contains("Route not found");
}

#[tokio::test]
async fn test_metrics() {
    let server = get_server();

    let response = server.get(METRICS_ROUTE).await;
    response.assert_status_ok();
    assert_eq!(response.header("content-type"), "text/plain; charset=utf-8");
}
```

So at first I was getting this error for all but one of the tests in that file:

```bash
called `Result::unwrap()` on an `Err` value: FailedToSetGlobalRecorder(SetRecorderError { .. })
```

After some research I instead used the branch you have with the alternative initialise method (#52) by putting this in `Cargo.toml`:

```toml
axum-prometheus = { git = "https://github.com/Ptrskay3/axum-prometheus", branch = "change-default-prometheus-recorder" }
```

Which now gets me to this error:

```bash
Failed to build metrics recorder: FailedToCreateHTTPListener("Address already in use (os error 98)")
```

---

Now, I'm a complete noob at all of this so let me know if I'm wrong, but it looks like the tests from the one file are all getting run at the same time, and the recorder needs some specific route for itself and so fails building?

This does not affect other integration tests, as they are all each just one test function per file. Running the above tests in separate files does solve the issue, but is there any way to avoid this while keeping all the tests together? No problem if there isn't, appreciate the help either way.

**Comment by Ptrskay3** [comment]
Overall, I'd recommend getting rid of the metrics layer in your tests (unless that's the part you wish to test), it'll be much less of an issue.

In Rust by default all tests are run in parallel. The root of your problem is that the `metrics` exporter is initialized globally. Assuming in your example `get_server` is always trying to initialize it, hence only the fastest test will have a chance to run  successfully, and the rest will fail. If you still prefer to have metrics in the tests, you may use [`std::sync::Once`](https://doc.rust-lang.org/std/sync/struct.Once.html) to run a one-time global initialization, and setup the metrics there [similar to this](https://github.com/Ptrskay3/axum-prometheus/blob/aaf0a29215837a9bab10e9af3dd216a01d3c76ee/src/lib.rs#L739-L752). Probably best way to use the `BaseMetricLayer` from the in-progress PR you already mentioned.

**Comment by Rolv-Apneseth** [comment]
I see thank you. I will likely either move them all into one test function or separate files if that is the case, as ideally for the integration test I want everything to be initialised the same way as it would be in the main function.

Do you know why it's not an issue if the tests are in separate files? Are the integration test binaries run sequentially?

**Comment by Ptrskay3** [comment]
Well, it depends on details how you run them, but probably the global metrics exporter initialization is isolated.

**Comment by Rolv-Apneseth** [comment]
Ah ok I get it. Thank you for the help, and thanks again for making this.
